# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(493, 672)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(400, 600))
        MainWindow.setMaximumSize(QtCore.QSize(2560, 1080))
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.WelcomeLabel = QtWidgets.QTextBrowser(self.centralwidget)
        self.WelcomeLabel.setMaximumSize(QtCore.QSize(16777215, 35))
        self.WelcomeLabel.setObjectName("WelcomeLabel")
        self.gridLayout.addWidget(self.WelcomeLabel, 0, 0, 1, 2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.listaTxt = QtWidgets.QListWidget(self.centralwidget)
        self.listaTxt.setMaximumSize(QtCore.QSize(16777215, 300))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.listaTxt.setFont(font)
        self.listaTxt.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listaTxt.setObjectName("listaTxt")
        self.verticalLayout.addWidget(self.listaTxt)
        self.prefButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prefButton.sizePolicy().hasHeightForWidth())
        self.prefButton.setSizePolicy(sizePolicy)
        self.prefButton.setMaximumSize(QtCore.QSize(16777215, 50))
        self.prefButton.setObjectName("prefButton")
        self.verticalLayout.addWidget(self.prefButton)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.subscelteLstView = QtWidgets.QListView(self.centralwidget)
        self.subscelteLstView.setMaximumSize(QtCore.QSize(16777215, 300))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.subscelteLstView.setFont(font)
        self.subscelteLstView.setAutoFillBackground(False)
        self.subscelteLstView.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.subscelteLstView.setAutoScrollMargin(16)
        self.subscelteLstView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.subscelteLstView.setAlternatingRowColors(True)
        self.subscelteLstView.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.subscelteLstView.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.subscelteLstView.setBatchSize(100)
        self.subscelteLstView.setObjectName("subscelteLstView")
        self.verticalLayout_3.addWidget(self.subscelteLstView)
        self.modificaButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modificaButton.sizePolicy().hasHeightForWidth())
        self.modificaButton.setSizePolicy(sizePolicy)
        self.modificaButton.setMaximumSize(QtCore.QSize(16777215, 50))
        self.modificaButton.setObjectName("modificaButton")
        self.verticalLayout_3.addWidget(self.modificaButton)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.numPostdaSalvare = QtWidgets.QSpinBox(self.centralwidget)
        self.numPostdaSalvare.setMinimum(1)
        self.numPostdaSalvare.setMaximum(1000)
        self.numPostdaSalvare.setProperty("value", 100)
        self.numPostdaSalvare.setObjectName("numPostdaSalvare")
        self.horizontalLayout.addWidget(self.numPostdaSalvare)
        self.aggiornaButton = QtWidgets.QPushButton(self.centralwidget)
        self.aggiornaButton.setObjectName("aggiornaButton")
        self.horizontalLayout.addWidget(self.aggiornaButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.postList = QtWidgets.QTreeView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.postList.sizePolicy().hasHeightForWidth())
        self.postList.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.postList.setFont(font)
        self.postList.setLineWidth(1)
        self.postList.setMidLineWidth(3)
        self.postList.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.postList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.postList.setTabKeyNavigation(False)
        self.postList.setAlternatingRowColors(True)
        self.postList.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.postList.setIndentation(20)
        self.postList.setHeaderHidden(True)
        self.postList.setObjectName("postList")
        self.postList.header().setVisible(False)
        self.postList.header().setCascadingSectionResizes(True)
        self.postList.header().setMinimumSectionSize(30)
        self.verticalLayout_2.addWidget(self.postList)
        self.gridLayout.addLayout(self.verticalLayout_2, 2, 0, 1, 2)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_4.addWidget(self.progressBar)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.salvaButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.salvaButton.setObjectName("salvaButton")
        self.horizontalLayout_2.addWidget(self.salvaButton)
        self.salvaDirButton = QtWidgets.QToolButton(self.centralwidget)
        self.salvaDirButton.setObjectName("salvaDirButton")
        self.horizontalLayout_2.addWidget(self.salvaDirButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.WelcomeLabel.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Benvenuto su </span><span style=\" font-size:12pt; font-weight:600;\">RSU</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "File delle liste di subreddit"))
        self.prefButton.setText(_translate("MainWindow", "Crea Preferito"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt; font-weight:600;\">Subreddit di interesse</span></p></body></html>"))
        self.modificaButton.setText(_translate("MainWindow", "Modifica Subs"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Quanti post upvotati vuoi vedere?</span></p></body></html>"))
        self.aggiornaButton.setText(_translate("MainWindow", "Aggiorna"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt; font-weight:600; font-style:italic; color:#55aa00;\">Upvotes</span></p></body></html>"))
        self.salvaButton.setText(_translate("MainWindow", "Salva gli Upvotes"))
        self.salvaDirButton.setText(_translate("MainWindow", "Dove Salvare?"))

